package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GarantieAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGarantieAllPropertiesEquals(Garantie expected, Garantie actual) {
        assertGarantieAutoGeneratedPropertiesEquals(expected, actual);
        assertGarantieAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGarantieAllUpdatablePropertiesEquals(Garantie expected, Garantie actual) {
        assertGarantieUpdatableFieldsEquals(expected, actual);
        assertGarantieUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGarantieAutoGeneratedPropertiesEquals(Garantie expected, Garantie actual) {
        assertThat(actual)
            .as("Verify Garantie auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGarantieUpdatableFieldsEquals(Garantie expected, Garantie actual) {
        assertThat(actual)
            .as("Verify Garantie relevant properties")
            .satisfies(a -> assertThat(a.getTypeMEG()).as("check typeMEG").isEqualTo(expected.getTypeMEG()))
            .satisfies(a -> assertThat(a.getCodeOffre()).as("check codeOffre").isEqualTo(expected.getCodeOffre()))
            .satisfies(a -> assertThat(a.getDateEffet()).as("check dateEffet").isEqualTo(expected.getDateEffet()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGarantieUpdatableRelationshipsEquals(Garantie expected, Garantie actual) {
        assertThat(actual)
            .as("Verify Garantie relationships")
            .satisfies(a -> assertThat(a.getProduit()).as("check produit").isEqualTo(expected.getProduit()));
    }
}
